### ISSUE TITLE
problem when hovering over the link icon

### ISSUE THREAD

**Issue by Arhell** [laminas/laminas.github.io#112]
### Bug Report

|    Q        |   A
|------------ | ------
| master  | now

#### Summary
![2](https://user-images.githubusercontent.com/26163841/93189575-f77c9900-f74a-11ea-837a-ab6425a6d423.jpg)

#### Current behavior

Problem when hovering over the icon

#### How to reproduce
Move the mouse over the icon and remove

#### Expected behavior
Underline should not be if you look at the styles

**Comment by froschdesign** [comment]
> underline should not be if you look at the styles

It's a normal link of the content section:

https://github.com/laminas/laminas.github.io/blob/28f0fbc81e3821ff12d8ae5fdcd6d6d2a2c088f7/asset/sass/blocks/_content.scss#L63-L72

---

Btw. Is your shift key broken? 😉

**Comment by Arhell** [comment]
> > underline should not be if you look at the styles
> 
> It's a normal link of the content section:
> 
> https://github.com/laminas/laminas.github.io/blob/28f0fbc81e3821ff12d8ae5fdcd6d6d2a2c088f7/asset/sass/blocks/_content.scss#L63-L72
> 
> Btw. Is your shift key broken? 😉

No, but the state of the link is different, that is, another line may appear, etc.
I propose to make the underline or not.
If yes, then remove these bugs on hover

**Comment by froschdesign** [comment]
Please create a pull request and we can then see exactly what you mean.
