### ISSUE TITLE
Add favicons for all devices and browsers

### ISSUE THREAD

**Issue by Arhell** [laminas/laminas.github.io#175]
### Feature Request

[
](https://realfavicongenerator.net/favicon_checker?protocol=https&site=docs.laminas.dev%2F#.ZBmgAXZBy3A)
|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no
| BC Break    | no

Ideally, create an RFC on our forums (https://discourse.laminas.dev/c/contributors)
to get feedback and flesh out the design, and link to it here.
-->

**Comment by froschdesign** [comment]
A few steps are needed here:

- Add all favicons to https://github.com/laminas/getlaminas.org
- Update the [theme](https://github.com/laminas/documentation-theme/blob/48c89f165d6a606557b051566c4c1a599278038b/theme/main.html#L24)
- Update all HTML files in this repository
