### ISSUE TITLE
Add table of contents to overview pages

### ISSUE THREAD

**Issue by froschdesign** [laminas/laminas.github.io#74]
A table of contents can help to provide a first overview and to navigate faster within the site.

The TOC for the Components overview would include:

* Config
* Filtering and Validation
* HTTP and URI
* Navigation and Pagination
* …

https://docs.laminas.dev/components/

And the Mezzio overview:

* API
* Authentication
* Authorization
* Session

https://docs.mezzio.dev/

### Example

![laminas github io_components_index html](https://user-images.githubusercontent.com/103362/82224445-23fee080-9924-11ea-84a0-f55dce13bce4.png)

**Comment by weierophinney** [comment]
:+1: on this!
